[project]
name = "2dmultibkgexperimental"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.14.0",
    "lightning>=2.5.5",
    "matplotlib>=3.10.6",
    "opencv-python-headless>=4.12.0.88",
    "scikit-image>=0.25.2",
    "scipy>=1.15.3",
    "tensorboard>=2.20.0",
    "torchinfo>=1.8.0",
    "plotly>=5.0.0",
    "k3d>=2.16.0",
    "napari[pyqt5]>=0.4.18",
    "torchvision>=0.17.0",
]
